# Generated by Django 4.0.6 on 2024-03-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_b_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='B_id',
        ),
    ]
