# Generated by Django 4.0.6 on 2024-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.BigIntegerField(default=1),
        ),
    ]
