# Generated by Django 4.0.6 on 2024-03-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_book_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='page',
        ),
        migrations.RemoveField(
            model_name='member',
            name='outstanding_debt',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_returned',
        ),
    ]
